- type: entity
  id: CrateServiceJanitorialSupplies
  parent: CratePlastic
  name: janitorial supplies crate
  description: Fight back against dirt and grime with Nanotrasen's Janitorial Essentials(tm)! Contains three buckets, caution signs, and cleaner grenades. Also has a single mop, broom, spray cleaner, rag, and trash bag.
  components:
  - type: StorageFill
    contents:
      - id: MopItem
      - id: MopBucketCubeWrapped
      - id: Bucket
        amount: 3
      - id: WetFloorSign
        amount: 2
      - id: Soap
      - id: SprayBottleSpaceCleaner
        amount: 2
      - id: TrashBag
        amount: 2
      - id: Plunger
        amount: 2
      - id: BoxCleanerGrenades

- type: entity
  id: CrateServiceReplacementLights
  parent: CrateGenericSteel
  name: replacement lights crate
  description: May the light of Aether shine upon this station! Or at least, the light of forty two light tubes and twenty one light bulbs.
  components:
  - type: StorageFill
    contents:
      - id: BoxLighttube
      - id: BoxLightbulb

- type: entity
  id: CrateServiceHolidayLights
  parent: CrateGenericSteel
  name: holiday lights crate
  description: Deck the halls with these festive holiday lights!
  components:
  - type: StorageFill
    contents:
      - id: BoxLighttubeHoliday
      - id: BoxLighttubeHoliday

- type: entity
  id: CrateMousetrapBoxes
  parent: CrateGenericSteel
  name: mousetraps crate
  description: Mousetraps, for when all of service is being haunted by an entire horde of rats. Use sparingly... or not.
  components:
    - type: StorageFill
      contents:
        - id: BoxMousetrap

- type: entity
  id: CrateServiceSmokeables
  parent: CrateGenericSteel
  name: smokeables crate
  description: Tired of a quick death on the station? Order this crate and chain-smoke your way to a coughy demise!
  components:
  - type: StorageFill
    contents:
      - id: CigCartonGreen
        prob: 0.50
        orGroup: CigCarton1
      - id: CigCartonRed
        orGroup: CigCarton1
      - id: CigCartonBlue
        prob: 0.50
        orGroup: CigCarton2
      - id: CigCartonBlack
        orGroup: CigCarton2
      - id: CigarGoldCase
        prob: 0.05
        orGroup: Cigars
      - id: CigarCase
        orGroup: Cigars
      - id: Matchbox
        amount: 2

- type: entity
  id: CrateServiceTheatre
  parent: CrateGenericSteel
  name: theatrical performances crate
  description: Contains a moth cloak, barber scissors, maid uniform, clown and mime attributes, and other performance charms.
  components:
  - type: StorageFill
    contents:
    - id: ClothingUniformJumpskirtPerformer
    - id: ClothingShoesBootsPerformer
    - id: ClothingHeadPerformerWig
    - id: ClothingOuterSuitMonkey
    - id: ClothingHeadHatAnimalMonkey
    - id: ClothingNeckCloakMoth
    - id: ClothingMaskClown
    - id: ClothingMaskMime
    - id: ClothingShoesClown
    - id: ClothingUniformJumpskirtJanimaid
    - id: ClothingNeckCloakVoid
    - id: RevolverCapGun
    - id: BarberScissors
    - id: ClothingUniformJumpskirtOldDress
    - id: BikeHorn
    - id: ClownRecorder
    - id: ClothingBeltSuspendersRed
    - id: ClothingBeltSuspendersBlack

- type: entity
  id: CrateServiceCustomSmokable
  parent: CrateGenericSteel
  name: DIY smokeables crate
  description: Want to get a little creative with what you use to destroy your lungs? Then this crate is for you! Has everything you need to roll your own cigarettes.
  components:
  - type: StorageFill
    contents:
    - id: PackPaperRolling
    - id: CigaretteFilter
      amount: 8
    - id: GroundTobacco
      amount: 4
    - id: SmokingPipe
    - id: Matchbox

- type: entity
  id: CrateServiceBureaucracy
  parent: CrateGenericSteel
  name: bureaucracy crate
  description: Several stacks of paper, a few pens and an office toy. What more could you ask for?
  components:
  - type: StorageFill
    contents:
    - id: Paper
      amount: 15
    - id: Pen
      amount: 2
    - id: BoxFolderClipboard
      amount: 2
    - id: HandLabeler
    - id: BoxFolderBlue
    - id: BoxFolderRed
    - id: BoxFolderYellow
    - id: NewtonCradle
    - id: BoxEnvelope
    - id: DeviceCalculator # SS220 Calculator
    - id: BrbSign

- type: entity
  id: CrateServiceFaxMachine
  parent: CrateGenericSteel
  name: fax machine crate
  description: A fax machine and a screwdriver to set the name with.
  components:
  - type: StorageFill
    contents:
    - id: Screwdriver
    - id: FaxMachineFlatpack

- type: entity
  id: CrateServicePersonnel
  parent: CrateCommandSecure
  name: personnel crate
  description: Contains a box of blank ID cards and PDAs.
  components:
  - type: StorageFill
    contents:
    - id: BoxPDA
    - id: BoxID

- type: entity
  id: CrateServiceBooks
  parent: CrateGenericSteel
  name: books crate
  description: Contains 10 empty books of random appearance.
  components:
    - type: StorageFill
      contents:
        - id: BookRandom
          amount: 10

- type: entity
  id: CrateServiceGuidebooks
  parent: CrateGenericSteel
  name: guidebooks crate
  description: Contains guidebooks.
  components:
    - type: StorageFill
      contents:
      - id: BookSpaceEncyclopedia
      - id: BookTheBookOfControl
      - id: BookBartendersManual
      - id: BookHowToCookForFortySpaceman
      - id: BookLeafLoversSecret
      - id: BookEngineersHandbook
      - id: BookScientistsGuidebook
      - id: BookSecurity
      - id: BookHowToKeepStationClean
      - id: BookHowToRockAndStone
      - id: BookMedicalReferenceBook
      - id: BookHowToSurvive
      - id: BookChemicalCompendium
      - id: BookSpaceLaws # SS220 Space Law Replace

- type: entity
  id: CrateServiceSodaDispenser
  parent: CrateGenericSteel
  name: soda dispenser refill crate
  description: Contains refills for soda dispensers.
  components:
    - type: StorageFill
      contents:
      - id: DrinkCoffeeJug
      - id: DrinkColaBottleFull
      - id: DrinkCreamCartonXL
      - id: DrinkDrGibbJug
      - id: DrinkEnergyDrinkJug
      - id: DrinkGreenTeaJug
      - id: DrinkIceJug
      - id: DrinkJuiceLimeCartonXL
      - id: DrinkJuiceOrangeCartonXL
      - id: DrinkLemonLimeJug
      - id: DrinkRootBeerJug
      - id: DrinkSodaWaterBottleFull
      - id: DrinkSpaceMountainWindBottleFull
      - id: DrinkSpaceUpBottleFull
      - id: DrinkSugarJug
      - id: DrinkTeaJug
      - id: DrinkTonicWaterBottleFull
      - id: DrinkWaterMelonJuiceJug

- type: entity
  id: CrateServiceBoozeDispenser
  parent: CrateGenericSteel
  name: booze dispenser refill crate
  description: Contains refills for booze dispensers.
  components:
    - type: StorageFill
      contents:
      - id: DrinkAleBottleFullGrowler
      - id: DrinkBeerGrowler
      - id: DrinkCoffeeLiqueurBottleFull
      - id: DrinkCognacBottleFull
      - id: DrinkGinBottleFull
      - id: DrinkMeadJug
      - id: DrinkRumBottleFull
      - id: DrinkTequilaBottleFull
      - id: DrinkVermouthBottleFull
      - id: DrinkVodkaBottleFull
      - id: DrinkWhiskeyBottleFull
      - id: DrinkWineBottleFull

- type: entity
  id: CrateServiceBox
  parent: CratePlastic
  name: boxes crate
  description: Contains 6 empty multipurpose boxes.
  components:
    - type: StorageFill
      contents:
        - id: BoxCardboard
          amount: 6

- type: entity
  id: CrateJanitorBiosuit
  parent: CratePlastic
  name: janitor bio suit crate
  description: Contains 2 biohazard suits to ensure that no disease will distract you from cleaning.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterBioJanitor
        amount: 2
      - id: ClothingHeadHatHoodBioJanitor
        amount: 2
      - id: ClothingMaskSterile
        amount: 2

- type: entity
  id: CrateTrashCartFilled
  suffix: Filled
  parent: CrateTrashCart
  components:
    #SS220 RatKing tweaks and changes start here
    - type: RatKingRummageable
      rummageLoot: RatKingLootTrashCans
    - type: RegalRatSpawnLocation
    #SS220 Ratking tweaks and changes end here
    - type: StorageFill
      contents:
          # Creatures
        - id: MobCockroach
          prob: 0.05
        - id: MobMothroach
          prob: 0.03
        - id: MobMouse
          prob: 0.05
          # Food Packaging
        - id: FoodPacketBoritosTrash
          prob: 0.1
        - id: FoodPacketCheesieTrash
          prob: 0.1
        - id: FoodPacketChipsTrash
          prob: 0.1
        - id: FoodPacketSusTrash
          prob: 0.1
        - id: FoodPacketSyndiTrash
          prob: 0.1
        - id: FoodPacketChowMeinTrash
          prob: 0.1
        - id: FoodPacketDanDanTrash
          prob: 0.1
        - id: FoodPacketMRETrash
          prob: 0.1
        - id: FoodPacketPistachioTrash
          prob: 0.1
        - id: FoodPacketSemkiTrash
          prob: 0.1
        - id: FoodPacketRaisinsTrash
          prob: 0.1
          # Cans
        - id: FoodTinBeansTrash
          prob: 0.15
        - id: FoodTinPeachesTrash
          prob: 0.15
        - id: FoodTinMRETrash
          prob: 0.15
          # Cigarette Stuff
        - id: Ash
          prob: 0.15
        - id: CigaretteSpent
          prob: 0.15
          # Bacteria
        - id: FoodBreadMoldySlice
          prob: 0.15
        - id: FoodPizzaMoldySlice
          prob: 0.15
          # Botanical Waste
        - id: TrashBananaPeel
          prob: 0.15
        - id: FoodCornTrash
          prob: 0.15
          # Misc
        - id: DrinkGlass
          prob: 0.15
        - id: BrokenBottle
          prob: 0.15
        - id: LightTubeBroken
          prob: 0.15
        - id: LightBulbBroken
          prob: 0.15
        - id: MobMouseDead
          prob: 0.1
        - id: Syringe
          prob: 0.1
        - id: ShardGlassPlasma
          prob: 0.1

- type: entity
  id: CrateCandles
  parent: CrateGenericSteel
  name: candles crate
  description: Contains 4 boxes of candles, 2 large and 2 small. For atmosphere or something.
  components:
  - type: StorageFill
    contents:
      - id: BoxCandle
        amount: 2
      - id: BoxCandleSmall
        amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceColorfulLights
  name: colorful lights crate
  description: It's not a party until it's hard to see, a little disorienting, and your ears hurt.
  components:
  - type: StorageFill
    contents:
    - id: BoxLightbulbColorfulMixed
    - id: BoxLighttubeColorfulMixed

# SS220-wood-and-plants-in-cargo-begin
- type: entity
  id: CratePottedPlant
  parent: CrateGenericSteel
  name: potted plant crate
  description: Contains one random potted plant for your station!
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomPottedPlantsTable

- type: entity
  id: CrateRandomPottedPlants
  parent: CrateGenericSteel
  name: potted plants crate
  description: Contains five random potted plants for your station! This is a better deal.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomPottedPlantsTable
        rolls: !type:ConstantNubmerSelector
          value: 5
- type: entity
  id: CrateBioLumPottedPlant
  parent: CrateGenericSteel
  name: potted bioluminescent plant crate
  description: Contains one exclusive random bioluminescent potted plant for your station! Wow... it's glowing.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomPottedBioLumPlantsTable

- type: entity
  id: CrateRandomBioLumPottedPlants
  parent: CrateGenericSteel
  name: potted bioluminescent plants crate
  description: Contains five exclusive random bioluminescent potted plants for your station! Wow... it's glowing. This is a better deal.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomPottedBioLumPlantsTable
        rolls: !type:ConstantNubmerSelector
          value: 5

- type: entity
  id: CratePlasticPottedPlant
  parent: CrateGenericSteel
  name: potted plastic plant crate
  description: Contains one cheap random plastic potted plant for your station! It looks like the real thing.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomPottedPlasticPlantsTable

- type: entity
  id: CrateRandomPlasticPottedPlants
  parent: CrateGenericSteel
  name: potted plastic plants crate
  description: Contains five cheap ones random plastic potted plants for your station! It looks like the real thing. This is a better deal?..
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: RandomPottedPlasticPlantsTable
        rolls: !type:ConstantNubmerSelector
          value: 5

- type: entityTable
  id: RandomPottedPlantsTable
  table: !type:GroupSelector
    children: 
      - id: PottedPlantAlt0
      - id: PottedPlantAlt1
      - id: PottedPlantAlt2
      - id: PottedPlantAlt3
      - id: PottedPlantAlt4
      - id: PottedPlant0
      - id: PottedPlant1
      - id: PottedPlant2
      - id: PottedPlant3
      - id: PottedPlant4
      - id: PottedPlant5
      - id: PottedPlant6
      - id: PottedPlant7
      - id: PottedPlant8
      - id: PottedPlant10
      - id: PottedPlant11
      - id: PottedPlant12
      - id: PottedPlant13
      - id: PottedPlant14
      - id: PottedPlant15
      - id: PottedPlant16
      - id: PottedPlant17
      - id: PottedPlant18
      - id: PottedPlant19
      - id: PottedPlant20
      - id: PottedPlant21
      - id: PottedPlant22
      - id: PottedPlant23
      - id: PottedPlant24
      - id: PottedPlant26

- type: entityTable
  id: RandomPottedBioLumPlantsTable
  table: !type:GroupSelector
    children: 
    - id: PottedPlantBioluminscentSS220_1
    - id: PottedPlantBioluminscentSS220_2
    - id: PottedPlantBioluminscentSS220_3
    - id: PottedPlantBioluminscentSS220_4
    - id: PottedPlantBioluminscentSS220_5
    - id: PottedPlantBioluminscentSS220_6
    - id: PottedPlantBioluminscentSS220_7
    - id: PottedPlantBioluminscentSS220_8
    - id: PottedPlantBioluminscentSS220_9
    - id: PottedPlantBioluminscentSS220_10
    - id: PottedPlantBioluminscentSS220_11
    - id: PottedPlantBioluminscentSS220_12
    - id: PottedPlantBioluminscentSS220_13
    - id: PottedPlantBioluminscentSS220_14
    - id: PottedPlantBioluminscentSS220_15
    - id: PottedPlantBioluminscentSS220_16
    - id: PottedPlantBioluminscentSS220_17
    - id: PottedPlantBioluminscentSS220_18
    - id: PottedPlantBioluminscentSS220_19
    - id: PottedPlantBioluminscentSS220_20
    - id: PottedPlantBioluminscentSS220_21
    - id: PottedPlantBioluminscentSS220_22
    - id: PottedPlantBioluminscentSS220_23
    - id: PottedPlantBioluminscentSS220_23
    - id: PottedPlantBioluminscentSS220_24
    - id: PottedPlantBioluminscentSS220_25
    - id: PottedPlantBioluminscentSS220_26
    - id: PottedPlantBioluminscentSS220_27
    - id: PottedPlantBioluminscentSS220_28
    - id: PottedPlantBioluminscentSS220_29
    - id: PottedPlantBioluminscentSS220_30
    - id: PottedPlantBioluminscent

- type: entityTable
  id: RandomPottedPlasticPlantsTable
  table: !type:GroupSelector
    children: 
    - id: PottedPlant27
    - id: PottedPlant28
    - id: PottedPlant29
    - id: PottedPlant30
# SS220-wood-and-plants-in-cargo-end